In [1]:
import numpy as np

## part 3-2

In [2]:
a=np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [3]:
import time
a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c=np.dot(a, b)
toc=time.time()

print(c)
print("Vectorized version : "+str(1000*(toc-tic))+"ms")

c=0

tic=time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()

print(c)
print("for loop : "+str(1000*(toc-tic))+"ms")

250159.62793745537
Vectorized version : 0.9639263153076172ms
250159.62793745543
for loop : 696.7043876647949ms


## part 3-5

In [4]:
A=np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.9, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.9  99.    0.9]]


In [5]:
cal=A.sum(axis=0)
print(cal)

[ 59.  239.9 155.4  76.9]


In [7]:
percentage=100*A/cal#.reshape(1, 4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.35139642 33.46203346 10.40312094]
 [ 3.05084746 56.64860358 63.70656371  1.17035111]]


## part 3-6

In [8]:
a=np.random.randn(5) ##definitly needs a shape!
print(a)

[ 0.09525546 -0.83402932 -0.35663819 -2.79503087  0.84429107]


In [9]:
print(a.shape)

(5,)


In [11]:
print(a.T)
print(a.T.shape)

[ 0.09525546 -0.83402932 -0.35663819 -2.79503087  0.84429107]
(5,)


In [12]:
print(np.dot(a, a.T))

9.35689428686608


In [13]:
a=np.random.randn(5,1)
print(a)

[[ 0.04371667]
 [-0.71301563]
 [ 1.19976515]
 [-1.4707101 ]
 [-0.84259702]]


In [14]:
print(a.T)

[[ 0.04371667 -0.71301563  1.19976515 -1.4707101  -0.84259702]]


In [15]:
assert(a.shape==(5,1))

## part 3-7